### ISSUE TITLE
Lower ALLOWED_SLIPPAGE to 1% and TOKEN_ALLOWED_SLIPPAGE to 2%

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#261]

**Comment by kcpark1** [comment]
Request: Allow user to set their own maximum allowed slippage 

p.s: 1.5% slippage does not stop the front running bot from being successful (as proven by using the .ch fork)

**Comment by haydenadams** [comment]
@kcpark1  agreed, these will be the new defaults but there will also be an adjustable parameter

**Comment by OliverNChalk** [comment]
I think an adjustable parameter will be the way to go. Power users should be able to set the slippage to 0% and simply have the transaction fail if someone enters a trade before them.

**Comment by MicahZoltu** [comment]
The current combination of slippage allowance plus front running bots means that Uniswap _effectively_ has about a 4.5% spread rather than the desired 0.6% spread.  This makes Uniswap significantly less compelling to use.  It would be nice if adding dynamic slippage was supported sooner rather than later so users can use Uniswap without getting fleeced by front-runners.
----
If one wants to run Uniswap UI locally, how would they go about modifying the slippage (file/line number)?

**Comment by MicahZoltu** [comment]
To answer my own question, if you want to edit the UI to have smaller slippage then you can adjust these lines: https://github.com/Uniswap/uniswap-frontend/blob/beta/src/pages/Send/index.js#L30-L31

**Comment by NoahZinsmeister** [comment]
closed via #369
