### ISSUE TITLE
AlphaWallet iOS no longer detectable on Uniswap

### ISSUE THREAD

**Issue by James-Sangalli** [Uniswap/uniswap-frontend#282]
It was working in the not so distant past but now when you access your site via the dapp browser, it states that the wallet is not connected anymore.

I am investigating this issue on the iOS side but do let me know of any potential changes that could have changed this.

**Comment by NoahZinsmeister** [comment]
does it work on beta.uniswap.io?

**Comment by NoahZinsmeister** [comment]
does it work on beta.uniswap.io?

**Comment by James-Sangalli** [comment]
No, same issue.

**Comment by zhangzhongnan928** [comment]
Both uniswap.exchange and beta.uniswap.exchange are not working in Cipher.
Same issue "No Ethereum wallet found" @petejkim

**Comment by haydenadams** [comment]
Cipher (which is now deprecated) is also not working for me.

Trust, Coinbase Wallet, Metamask, Status, OperaTouch all work though (on iOS).

We will def look into it - but I'd say something the team at Alpha Wallet should look into as well since it works with so many other wallets. Have you seen anything similar to this @zhangzhongnan928?

**Comment by zhangzhongnan928** [comment]
> Cipher (which is now deprecated) is also not working for me.
> 
> Trust, Coinbase Wallet, Metamask, Status, OperaTouch all work though (on iOS).
> 
> We will def look into it - but I'd say something the team at Alpha Wallet should look into as well since it works with so many other wallets. Have you seen anything similar to this @zhangzhongnan928?

Yes, we are looking into it. I'm using Uniswap all the time, need to fix it asap.
I tested it on 20 different web3 wallets, it seems only effect Cipher and AlphaWallet.
We haven't figured out why.

**Comment by James-Sangalli** [comment]
We are using web3 0.20.6, it gives a CORS issue from infura

[Error] Fetch API cannot load https://mainnet.infura.io/v3/60ab76e16df54c808e50a79975b4779f due to access control checks.

We have had a similar issue before with some versions of web3.js that contain bugs

**Comment by NoahZinsmeister** [comment]
@James-Sangalli the infamous CORS problem..strange that it's coming up in this context though, as right now uniswap.exchange only makes calls to infura if the injected web3 provider can't be enabled, and in any case that shouldn't break because of your web3,js version, as we're bundling our own version to communicate with infura.

**Comment by James-Sangalli** [comment]
@NoahZinsmeister did you upgrade your version of web3?

**Comment by James-Sangalli** [comment]
@NoahZinsmeister does uniswap rely on the devices web3 or its own? Seems this is unpredictable and sometimes changing our web3 version internally breaks other dapp websites.

**Comment by zhangzhongnan928** [comment]
TokenPocket has the same issue @erichin

**Comment by James-Sangalli** [comment]
@NoahZinsmeister I noticed that the website will not load at all if you don't have a web3 provider in your window (when running on your local server), is it possible that the upgrade of your web3 dependency has bugs?

**Comment by NoahZinsmeister** [comment]
i'm going to be debugging the cipher/alphawallet/tokenpocket issue soon™, hopefully this monday and tuesday. @James-Sangalli we're actually using ethers.js locally, but again this shouldn't affect your code and vice versa.

**Comment by NoahZinsmeister** [comment]
alright, the reason this is broken is because all of the aforementioned providers ^ set the `window.web3` property, not the more modern `window.ethereum` per [EIP-1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md). we will publish a hot-fix for this soon, but please take this as a strong suggestion to upgrade your provider logic :)

**Comment by James-Sangalli** [comment]
@NoahZinsmeister thanks for your suggestion. I added the window.ethereum object and checked it on the mobile console but it still doesn't work. 

<img width="969" alt="Screen Shot 2019-05-21 at 9 04 10 am" src="https://user-images.githubusercontent.com/16630514/58057322-ca949200-7ba7-11e9-88c2-d0be4483ec7e.png">

**Comment by James-Sangalli** [comment]
It was the enable object, fixed here: https://github.com/AlphaWallet/AlphaWallet-web3-provider/pull/5 

Cheers (was still valuable to add the window.ethereum object too)
