### ISSUE TITLE
Adding to USDT Liquidity Pool is Impossible

### ISSUE THREAD

**Issue by ccashwell** [Uniswap/uniswap-frontend#362]
**Bug Description**
It is impossible to add liquidity to the ETH/USDT pool. The pool exists and has no liquidity but any attempt to add to it throws a MetaMask "Internal RPC Error" console message.

**Steps to Reproduce**
1. Go to https://uniswap.exchange/add-liquidity
2. Paste the USDT token address (0xdac17f958d2ee523a2206206994597c13d831ec7)
2a. If needed, unlock USDT for trading
3. Attempt to add liquidity of any amount, for example 1 ETH + 272 USDT
4. Observe silent failure.
5. Open dev console to find the error:
![image](https://user-images.githubusercontent.com/184242/61146038-01e83680-a4a7-11e9-929b-f32c6d6999a2.png)

**Expected Behavior**
Users should be able to add liquidity to the USDT pool.

**Comment by haydenadams** [comment]
Unfortunately USDT has the same bug as OMG and BNB:

https://medium.com/coinmonks/missing-return-value-bug-at-least-130-tokens-affected-d67bf08521ca

We're looking into two options to deal with these types of tokens:

1) factory for wrapping tokens - turn BNB into WBNB, OMG into WOMG, etc...
This is nice because these wrapped tokens can be used across all of DEFI, not just Uniswap

2) factory for custom uniswap pools that doesnt do `assert` on transfer. 
This would eliminate the need to wrap on Uniswap but requires some special handling for ERC20 to ERC20 swaps and would not help out other DEFI dapps

**Comment by ccashwell** [comment]
@haydenadams makes sense, thanks for the clarity. It'd be really great to see OMG, BNB, USDT and other non-returning tokens come to Uniswap (and other DeFi platforms, too).

It seems to me the wrapper would be a workable solution. It does require extra work on the part of users which is always a hassle, but so does WETH and that's obviously very heavily used in the community.

**Comment by haydenadams** [comment]
Once the wrapper is set up we could also create a helper contract that wraps and swaps in a single tx, which would essentially mimic the current UX at a higher gas cost for these tokens.
