### ISSUE TITLE
Uniswap no longer works with Frame

### ISSUE THREAD

**Issue by john-light** [Uniswap/uniswap-frontend#414]
**Bug Description**
A couple of weeks ago, I used Uniswap with [Frame](https://frame.sh) to do an exchange and it worked. Today, I tried to use Uniswap with Frame and it doesn't work anymore. When I use Uniswap with MetaMask instead it does work, and MetaMask pops up a request for Uniswap to access my account.

**Steps to Reproduce**
1. Install Frame
2. Plug in Ledger and open account in Frame
3. Visit Uniswap exchange
4. Click "Connect to a wallet" and select "Injected"
5. See that Uniswap never connects to Frame:

![Screenshot_2019-12-06 Uniswap Exchange](https://user-images.githubusercontent.com/9424721/70301701-17009180-17c9-11ea-8772-5900004f58a2.png)

**Expected Behavior**
I expect the Uniswap exchange to load so I can swap tokens.

**Additional Context**
Since MetaMask worked and Frame didn't maybe Uniswap made a change that broke the connection to Frame. Maybe a change to how Uniswap uses Web3?

**Comment by NoahZinsmeister** [comment]
@john-light could you open up your console and report any errors that you see?

**Comment by john-light** [comment]
It actually seems to be working now so I am closing this issue. It must have been some other kind of connection issue earlier.

**Comment by john-light** [comment]
Re-opening as I am experiencing this error consistently again.

**Comment by NoahZinsmeister** [comment]
will look into this shortly!

**Comment by NoahZinsmeister** [comment]
@john-light i think it's a race condition of some kind on frame's end. we're recovering from the failed `'eth_requestAccounts'` call, and `'enable'` is returning the proper account, but then we call `'eth_chainId'` and `'net_version'` in succession, both of which return `'Not connected to Ethereum network'` errors with code `-1`. these calls don't fail by just calling the methods directly on `window.ethereum`, but something about the `enable` call must be causing the internals of the provider to return this error. any thoughts?

for reference i'm using frame 0.2.4 via the browser extension 0.1.5.

**Comment by john-light** [comment]
@NoahZinsmeister I don't know what any of that means, but I have opened an issue in the Frame repo linking to your comment so hopefully we can resolve this!

https://github.com/floating/frame/issues/308

Will close this issue and track in the Frame repo for now.

**Comment by floating** [comment]
@john-light and @NoahZinsmeister 

Since Frame `0.2.4` does not handle `eth_requestsAccounts` the payload is passed along to the user's connected node. In the default case is Infura, when Infura receives the method `eth_requestsAccounts` it closes the socket connection. Frame then reconnects but not quickly enough for the `eth_chainId` and `net_version` calls resulting in 'Not connected to Ethereum network' errors. 

![Screen Shot 2019-12-06 at 3 58 27 PM](https://user-images.githubusercontent.com/598504/70356315-1d7f1f80-1842-11ea-8101-c6a4bb037005.png)

I will be pushing a fix to the browser extension shortly to return an error for `eth_requestsAccounts` payloads until `eth_requestsAccounts` support is available in the next version of Frame.
