### ISSUE TITLE
Token Request: GUSD

### ISSUE THREAD

**Issue by kingjacob** [Uniswap/uniswap-frontend#485]
**Please provide the following information for your token.**

Token Address: 0x056fd409e1d7a124bd7017459dfea2f387b6d5cd
Token Name (from contract): Gemini dollar
Token Decimals (from contract): 2
Token Symbol (from contract): GUSD
Uniswap Exchange Address of Token: 0xd883264737ed969d2696ee4b4caf529c2fc2a141

Link to the official homepage of the token: https://gemini.com/dollar/
Link to Coinmarketcap page of token: https://coinmarketcap.com/currencies/gemini-dollar/

Test swap transaction: https://etherscan.io/tx/0x9cb6f7eb98124388869f671dd5a466521063ed4830443d78e66aefff7057219d
Test addLiquidity transaction: https://etherscan.io/tx/0x35a9a6435acb243cdee97f3595263c8a3a6f65fa8f17cebb51fdd8b29fea77b0
Test removeToken transaction: https://etherscan.io/tx/0xdae0c09800c01a08e08af294370b56098ac16d8b80661e88ec90f1d0652e7c41

Are you able to add liquidity to the liquidity pool for this token? Yes.
If so, how much liquidity are you able to add (USD)? 1ETH

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time due to low platform liqudity, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
