### ISSUE TITLE
Infura connection

### ISSUE THREAD

**Issue by pcowgill** [Uniswap/uniswap-frontend#496]
Out of curiosity, is there a reason the connection to Infura is done with the bare bones [`JsonRpcProvider`](https://github.com/Uniswap/uniswap-frontend/blob/bb4d03501254348ae0245a7737850a012b5e56fb/src/NetworkOnlyConnector.js#L9) as opposed to the `InfuraProvider` from `ethers.js`?

[ethers.js provider docs](https://docs.ethers.io/ethers.js/html/api-providers.html)

It's very likely there's a good reason for doing it the way it's done now, so this issue is mostly to clarify the choice. I know `InfuraProvider` inherits from `JsonRpcProvider`, so this decision has pretty minimal implications either way. Thanks!

**Comment by NoahZinsmeister** [comment]
we're actually using an [`ethers.providers.Web3Provider`](https://github.com/Uniswap/uniswap-frontend/blob/38bb32504db03e653b0766e562786b408131795e/src/index.js#L21) for all connections now!

the reason that we're not using the infura-specific provider is because `web3-react` strongly encourages consistency in how libraries are initialized from providers, for a variety of reasons (primarily because the library needs to support initializing libraries across web3.js/ethers/etc., and because settling on a low-level provider object that connectors return is good for consistency/interop). that being said, we could of course special-case some of these on the uniswap side of things, but at the moment this doesn't seem worth it.
