### ISSUE TITLE
AlphaWallet web3 injection not detected

### ISSUE THREAD

**Issue by James-Sangalli** [Uniswap/uniswap-frontend#548]
Normally this works and was working not so long ago, however it can no longer detect the wallet anymore. 

This was reported by a user here: https://github.com/AlphaWallet/alpha-wallet-ios/issues/1613

Has something changed which requires action on our part? Thanks!

**Comment by NoahZinsmeister** [comment]
hey @James-Sangalli, thanks for the report. i can confirm that the bug is replicable on my end, sorry for the breaking change.

we indeed changed how we're doing some web3 handling recently. specifically, i narrowed the alphawallet issue down to an issue with how we're fetching chainId.

right now this function is failing: https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/injected-connector/src/index.ts#L105.

i was unable to figure out an easy fix (it's a bit hard to debug from my phone), do you have a snippet for how this fetch should be happening for alphawallet?

**Comment by James-Sangalli** [comment]
Hi @NoahZinsmeister thanks for the quick response!

I added getChainId to the web3 injection but still no luck: https://github.com/AlphaWallet/alpha-wallet-ios/commit/205a56125d216dae15faaa24162c0db038063c44

On the phone debugger it does not report an error, any ideas?

**Comment by NoahZinsmeister** [comment]
i'm not sure i understand, did you add a function to the window.ethereum object called `getChainId`? that won't do anything, the function i linked is trying a variety of things, first `window.ethereum.send('eth_chainId')`, then `window.ethereum.send('net_version')`, then some other ad-hoc stuff. the easiest way to make sure this function doesn't fail is to return the chain id for `window.ethereum.send('eth_chainId')` calls. if that's not possible, we can resort to ad-hoc methods for alphawallet in particular, but i'd prefer not to do that.

**Comment by James-Sangalli** [comment]
@NoahZinsmeister added that to the ethereum object and called it in the phone console:

<img width="445" alt="Screenshot 2019-12-22 12 30 46" src="https://user-images.githubusercontent.com/16630514/71315667-f158d500-24b6-11ea-96e7-29be95a88177.png">

Despite this, the website still doesn't work with the provider. Any other ideas?

**Comment by NoahZinsmeister** [comment]
@James-Sangalli this is fixed in the latest version of [web3-react](https://github.com/NoahZinsmeister/web3-react), ([sandbox link](https://codesandbox.io/s/web3-react-v6-8rg3h?fontsize=14&hidenavigation=1&theme=dark))which we're using to handle injected connectors. 

we'll bump our version shortly, which should fix this issue!

**Comment by James-Sangalli** [comment]
@NoahZinsmeister working, thank you!

**Comment by James-Sangalli** [comment]
@NoahZinsmeister seems to not be working again, any recent changes?

**Comment by NoahZinsmeister** [comment]
nope, nothing's changed recently @James-Sangalli

**Comment by James-Sangalli** [comment]
Haha @NoahZinsmeister indeed, problem was between keyboard and chair

**Comment by James-Sangalli** [comment]
For posterity, it was because the browser was set to a network that was not ethereum, hence the web3 provider could not find it as it was expecting the ethereum network.
