### ISSUE TITLE
Cipher Browser not working

### ISSUE THREAD

**Issue by PaulRBerg** [Uniswap/uniswap-frontend#565]
**Bug Description**
Cannot log in with the [Cipher Browser](https://www.cipherbrowser.com/).

**Steps to Reproduce**
1. Install Cipher Browser on iOS
2. Open uniswap.exchange.
3. Tap "Connect to a Wallet" and see no option to log in via the Injected connector

**Expected Behavior**
Should be able to log in.

**Additional Context**
Here's a screenshot taken on an iPhone XR running iOS 12.3.1

![IMG_6941](https://user-images.githubusercontent.com/8782666/70932299-16c28a80-2042-11ea-924a-eb5c4726bb6c.PNG)

**Comment by NoahZinsmeister** [comment]
Cipher was [acquired by Coinbase last year](https://techcrunch.com/2018/04/13/coinbase-acquires-decentralized-app-browser-wallet-cipher-browser/), and it seems like they're not actively developing the app anymore. The reason it doesn't work is because they're still using `window.web3` instead of `window.ethereum`. I'm inclined to simply consider the app as officially deprecated.

**Comment by PaulRBerg** [comment]
Okay. I'll close this for now, if anyone from Coinbase/ Cipher wants the wallet working with Uniswap/ Sablier, they should switch to `window.ethereum`. Thanks for confirming.
